//CREATE
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';
//READ
export const DOWNLOAD_PRODUCTS_START = 'DOWNLOAD_PRODUCTS_START';
export const DOWNLOAD_PRODUCTS_SUCCESS = 'DOWNLOAD_PRODUCTS_SUCCESS';
export const DOWNLOAD_PRODUCTS_ERROR = 'DOWNLOAD_PRODUCTS_ERROR';
//DELETE
export const GET_DELETE_PRODUCT = "GET_DELETE_PRODUCT";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";
//EDIT
export const GET_EDIT_PRODUCT = "GET_EDIT_PRODUCT";
export const EDIT_PRODUCT_START = "EDIT_PRODUCT_START";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_ERROR = "EDIT_PRODUCT_ERROR";

//ALERT REDUCER
export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDDEB_ALERT";
