//    --PRODUCTS--
//CREATE
export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";
//READ
export const DOWNLOAD_PRODUCTS_START = "DOWNLOAD_PRODUCTS_START";
export const DOWNLOAD_PRODUCTS_SUCCESS = "DOWNLOAD_PRODUCTS_SUCCESS";
export const DOWNLOAD_PRODUCTS_ERROR = "DOWNLOAD_PRODUCTS_ERROR";
//DELETE
export const GET_DELETE_PRODUCT = "GET_DELETE_PRODUCT";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";
//EDIT
export const GET_EDIT_PRODUCT = "GET_EDIT_PRODUCT";
export const EDIT_PRODUCT_START = "EDIT_PRODUCT_START";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_ERROR = "EDIT_PRODUCT_ERROR";

//SEARCH RESULTS
export const GET_SEARCH_RESULTS_START = "GET_SEARCH_RESULTS_START";
export const GET_SEARCH_RESULTS_SUCCESS = "GET_SEARCH_RESULTS_SUCCESS";
export const GET_SEARCH_RESULTS_ERROR = "GET_SEARCH_RESULTS_ERROR";
//ALERT REDUCER
export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDDEB_ALERT";

//   --REQUEST--
export const DOWNLOAD_REQUEST_START = "DOWNLOAD_REQUEST_START";
export const DOWNLOAD_REQUEST_SUCCESS = "DOWNLOAD_REQUEST_SUCCESS";
export const DOWNLOAD_REQUEST_ERROR = "DOWNLOAD_REQUEST_ERROR";

export const EDIT_REQUEST_START = "EDIT_REQUEST_START";
export const EDIT_REQUEST_SUCCESS = "EDIT_REQUEST_SUCCESS";
export const EDIT_REQUEST_ERROR = "EDIT_REQUEST_ERROR";

//SUMMARY
export const GET_SUMMARY_START = "GET_SUMMARY_START";
export const GET_SUMMARY_SUCCESS = "GET_SUMMARY_SUCCESS";
export const GET_SUMMARY_ERROR = "GET_SUMMARY_ERROR";

//company Actions
export const SETCATEGORIES_START = "SETCATEGORIES_START";
export const SETCATEGORIES_SUCCESS = "SETCATEGORIES_SUCCESS";
export const SETCATEGORIES_ERROR = "SETCATEGORIES_ERROR";

export const GET_INFOCOMPANY_START = "GET_INFOCOMPANY_START";
export const GET_INFOCOMPANY_ERROR = "GET_INFOCOMPANY_ERROR";
export const GET_INFOCOMPANY_SUCCESS = "GET_INFOCOMPANY_SUCCESS";

export const SET_INFOCOMPANY_START = "SET_INFOCOMPANY_START";
export const SET_INFOCOMPANY_ERROR = "SET_INFOCOMPANY_ERROR";
export const SET_INFOCOMPANY_SUCCESS = "SET_INFOCOMPANY_SUCCESS";

// --Auth_COMPANY--
export const AUTH_COMPANY_START = "AUTH_COMPANY_START";
export const AUTH_COMPANY_SUCCESS = "AUTH_COMPANY_SUCCESS";
export const AUTH_COMPANY_ERROR = "AUTH_COMPANY_ERROR";
export const GET_COMPANY_START = "GET_COMPANY_START";
export const GET_COMPANY_SUCCESS = "GET_COMPANY_SUCCESS";
export const GET_COMPANY_ERROR = "GET_COMPANY_ERROR";
export const LOGOUT = "LOGOUT";
